--------------------------------------------------------
--  File created - Sunday-May-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FAVORIT
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."FAVORIT" 
   (	"FAVORIT_ID" VARCHAR2(6 BYTE), 
	"USER_ID" VARCHAR2(6 BYTE), 
	"RESTO_ID" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."MENU" 
   (	"MENU_ID" VARCHAR2(6 BYTE), 
	"RESTO_ID" VARCHAR2(6 BYTE), 
	"IMG_MENU_1" BLOB, 
	"IMG_MENU_2" BLOB, 
	"IMG_MENU_3" BLOB, 
	"IMG_MENU_4" BLOB, 
	"IMG_MENU_5" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMG_MENU_1") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_2") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_3") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_4") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_5") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RESTORAN
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."RESTORAN" 
   (	"RESTO_ID" VARCHAR2(6 BYTE), 
	"NAMA_RESTO" VARCHAR2(50 BYTE), 
	"IMAGE" BLOB, 
	"LOKASI" VARCHAR2(250 BYTE), 
	"NO_TELP" VARCHAR2(16 BYTE), 
	"RANGE_HARGA" VARCHAR2(100 BYTE), 
	"WAKTU_BUKA" VARCHAR2(250 BYTE), 
	"HARI_BUKA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ULASAN
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."ULASAN" 
   (	"ULASAN_ID" VARCHAR2(6 BYTE), 
	"USER_ID" VARCHAR2(6 BYTE), 
	"RESTO_ID" VARCHAR2(6 BYTE), 
	"RATING" NUMBER(1,0), 
	"ULASAN_JUDUL" VARCHAR2(255 BYTE), 
	"ULASAN_DESKRIPSI" CLOB, 
	"MENU_DIPESAN" VARCHAR2(100 BYTE), 
	"HARGA_PER_ORANG" VARCHAR2(100 BYTE), 
	"FOTO_ULASAN" BLOB, 
	"TANGGAL_PERGI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ULASAN_DESKRIPSI") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FOTO_ULASAN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USER_NEMUMENU
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."USER_NEMUMENU" 
   (	"USER_ID" VARCHAR2(36 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD_USER" VARCHAR2(250 BYTE), 
	"NAMA_DEPAN" VARCHAR2(250 BYTE), 
	"NAMA_BELAKANG" VARCHAR2(250 BYTE), 
	"FOTO_PROFILE" BLOB, 
	"TANGGAL_LAHIR" DATE, 
	"JENIS_KELAMIN" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FOTO_PROFILE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into NEMU_MENU_USER.FAVORIT
SET DEFINE OFF;
REM INSERTING into NEMU_MENU_USER.MENU
SET DEFINE OFF;
Insert into NEMU_MENU_USER.MENU (MENU_ID,RESTO_ID) values ('MN001','RS001');
REM INSERTING into NEMU_MENU_USER.RESTORAN
SET DEFINE OFF;
Insert into NEMU_MENU_USER.RESTORAN (RESTO_ID,NAMA_RESTO,LOKASI,NO_TELP,RANGE_HARGA,WAKTU_BUKA,HARI_BUKA) values ('RS001','Nabila Steak','Jl. Gondang Timur II','08191995999','Rp 10.000 - Rp 25.000','Senin-Jumat (12.00-20.00)',null);
REM INSERTING into NEMU_MENU_USER.ULASAN
SET DEFINE OFF;
Insert into NEMU_MENU_USER.ULASAN (ULASAN_ID,USER_ID,RESTO_ID,RATING,ULASAN_JUDUL,MENU_DIPESAN,HARGA_PER_ORANG,TANGGAL_PERGI) values ('UL001','US002','RS001','5','Murce banget!! Bapak Ibu nya ramah!',null,null,null);
REM INSERTING into NEMU_MENU_USER.USER_NEMUMENU
SET DEFINE OFF;
Insert into NEMU_MENU_USER.USER_NEMUMENU (USER_ID,USERNAME,EMAIL,PASSWORD_USER,NAMA_DEPAN,NAMA_BELAKANG,TANGGAL_LAHIR,JENIS_KELAMIN) values ('US001','Faiza','faiza@gmail.com','$2y$12$8XRao0w56cCZv/2ufbMECeDlk1kbyoRd1Mu9tk.FgaqBtVmi6qrXu',null,null,null,null);
Insert into NEMU_MENU_USER.USER_NEMUMENU (USER_ID,USERNAME,EMAIL,PASSWORD_USER,NAMA_DEPAN,NAMA_BELAKANG,TANGGAL_LAHIR,JENIS_KELAMIN) values ('US002','aufa','aufa@gmail.com','$2y$12$BQt.5qP3OLN9eGmYdWpPouNydHCgf9bmP91gb.wUxty4SWAeJo0qS',null,null,null,null);
--------------------------------------------------------
--  DDL for Index FAVORIT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."FAVORIT_ID" ON "NEMU_MENU_USER"."FAVORIT" ("FAVORIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."MENU_ID" ON "NEMU_MENU_USER"."MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESTO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."RESTO_ID" ON "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ULASAN_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."ULASAN_ID" ON "NEMU_MENU_USER"."ULASAN" ("ULASAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."USER_ID" ON "NEMU_MENU_USER"."USER_NEMUMENU" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."USERNAME" ON "NEMU_MENU_USER"."USER_NEMUMENU" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."EMAIL" ON "NEMU_MENU_USER"."USER_NEMUMENU" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FAVORIT
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."FAVORIT" ADD CONSTRAINT "FAVORIT_ID" PRIMARY KEY ("FAVORIT_ID")
  USING INDEX "NEMU_MENU_USER"."FAVORIT_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."MENU" ADD CONSTRAINT "MENU_ID" PRIMARY KEY ("MENU_ID")
  USING INDEX "NEMU_MENU_USER"."MENU_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTORAN
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."RESTORAN" ADD CONSTRAINT "RESTO_ID" PRIMARY KEY ("RESTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ULASAN
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CHECK (rating BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CONSTRAINT "ULASAN_ID" PRIMARY KEY ("ULASAN_ID")
  USING INDEX "NEMU_MENU_USER"."ULASAN_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_NEMUMENU
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."USER_NEMUMENU" ADD CONSTRAINT "USER_ID" PRIMARY KEY ("USER_ID")
  USING INDEX "NEMU_MENU_USER"."USER_ID"  ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."USER_NEMUMENU" ADD CONSTRAINT "USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."USER_NEMUMENU" ADD CONSTRAINT "EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAVORIT
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."FAVORIT" ADD CONSTRAINT "USER_ID_FAV" FOREIGN KEY ("USER_ID")
	  REFERENCES "NEMU_MENU_USER"."USER_NEMUMENU" ("USER_ID") ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."FAVORIT" ADD CONSTRAINT "RESTO_ID_FAV" FOREIGN KEY ("RESTO_ID")
	  REFERENCES "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."MENU" ADD CONSTRAINT "RESTO_ID_MENU" FOREIGN KEY ("RESTO_ID")
	  REFERENCES "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ULASAN
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CONSTRAINT "USER_ID_UL" FOREIGN KEY ("USER_ID")
	  REFERENCES "NEMU_MENU_USER"."USER_NEMUMENU" ("USER_ID") ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CONSTRAINT "RESTO_ID_UL" FOREIGN KEY ("RESTO_ID")
	  REFERENCES "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") ENABLE;
